name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  release:
    name: Build a release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup version
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          VERSION=$(echo $REF_NAME | sed 's/^v//g')
          echo "Version: $VERSION"
          npm pkg set version="$VERSION"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish